version: "3"

services:
  mssql:
    container_name: 'mssql'
    image: mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04
    environment:
      SA_PASSWORD: 'secretpassw0rd!'
      ACCEPT_EULA: 'Y'
    ports:
      - "1433:1433"